/** @type {import('sequelize-cli').Migration} */
export default {
  async up(queryInterface, Sequelize) {
    const componentes = [
      // ==================== COMPONENTES GLOBAIS ====================
      {
        com_id: '550e8400-e29b-41d4-a716-446655470001',
        com_nome: 'header',
        com_descricao: 'Componente de cabeçalho com logo e navegação',
        com_tipo: 'global',
        com_possui_elementos: true,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470002',
        com_nome: 'footer',
        com_descricao: 'Componente de rodapé com links e informações',
        com_tipo: 'global',
        com_possui_elementos: true,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== COMPONENTES REUTILIZÁVEIS ====================
      {
        com_id: '550e8400-e29b-41d4-a716-446655470003',
        com_nome: 'carousel',
        com_descricao: 'Componente de carrossel de imagens',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470004',
        com_nome: 'ofertas',
        com_descricao: 'Componente exibindo ofertas especiais',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470005',
        com_nome: 'faq',
        com_descricao: 'Componente de perguntas frequentes',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470006',
        com_nome: 'helpSection',
        com_descricao: 'Componente de seção de ajuda',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470007',
        com_nome: 'banner',
        com_descricao: 'Componente de banner de destaque',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470008',
        com_nome: 'depoimentos',
        com_descricao: 'Componente de depoimentos de clientes',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470009',
        com_nome: 'contato',
        com_descricao: 'Componente de formulário de contato',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470010',
        com_nome: 'faixaPlanos',
        com_descricao: 'Componente exibindo faixa de planos',
        com_tipo: 'reutilizável',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== COMPONENTES ESPECÍFICOS ====================
      {
        com_id: '550e8400-e29b-41d4-a716-446655470011',
        com_nome: 'servicosEssenciais',
        com_descricao: 'Componente de serviços essenciais',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470012',
        com_nome: 'servicosEssenciaisInternet',
        com_descricao: 'Componente de serviços essenciais de internet',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470013',
        com_nome: 'infinitePossibilities',
        com_descricao: 'Componente de possibilidades infinitas',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470014',
        com_nome: 'appExclusivo',
        com_descricao: 'Componente do app exclusivo',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470015',
        com_nome: 'planoControle',
        com_descricao: 'Componente do plano controle',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470016',
        com_nome: 'telefoniaBanner',
        com_descricao: 'Componente de banner de telefonia',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470017',
        com_nome: 'porQueEscolher',
        com_descricao: 'Componente de por que escolher',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470018',
        com_nome: 'introducao',
        com_descricao: 'Componente de introdução',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470019',
        com_nome: 'servicos',
        com_descricao: 'Componente de serviços',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470020',
        com_nome: 'divisorSecao',
        com_descricao: 'Componente divisor de seção',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470021',
        com_nome: 'cardsEntretenimento',
        com_descricao: 'Componente de cards de entretenimento',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470022',
        com_nome: 'quemsomos',
        com_descricao: 'Componente de quem somos',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        com_id: '550e8400-e29b-41d4-a716-446655470023',
        com_nome: 'ofertaschips',
        com_descricao: 'Componente de ofertas de chips',
        com_tipo: 'específico',
        com_possui_elementos: false,
        com_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await queryInterface.bulkInsert('0004_Componente', componentes);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('0004_Componente', null, {});
  },
};
