/** @type {import('sequelize-cli').Migration} */
export default {
  async up(queryInterface, Sequelize) {
    const elementos = [
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480001',
        ele_nome: 'topBar',
        ele_descricao: 'Barra superior com contato rápido',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480002',
        ele_nome: 'logo',
        ele_descricao: 'Logo da marca',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480003',
        ele_nome: 'navigation',
        ele_descricao: 'Menu de navegação principal',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480004',
        ele_nome: 'searchBar',
        ele_descricao: 'Barra de busca',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480005',
        ele_nome: 'loginButton',
        ele_descricao: 'Botão de login/conta',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480006',
        ele_nome: 'socialLinks',
        ele_descricao: 'Links de redes sociais',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== FOOTER ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480009',
        ele_nome: 'socialMedia',
        ele_descricao: 'Links das redes sociais',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480010',
        ele_nome: 'locationSelector',
        ele_descricao: 'Seletor de localização',
        ele_habilitado: false,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480011',
        ele_nome: 'companyInfo',
        ele_descricao: 'Informações da empresa',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480012',
        ele_nome: 'columns',
        ele_descricao: 'Colunas de links',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480013',
        ele_nome: 'appLinks',
        ele_descricao: 'Links para downloads de app',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480014',
        ele_nome: 'copyright',
        ele_descricao: 'Texto de copyright',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== OFERTAS ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480015',
        ele_nome: 'headline',
        ele_descricao: 'Título principal das ofertas',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480016',
        ele_nome: 'toggleAll',
        ele_descricao: 'Botão para mostrar/ocultar todas',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480017',
        ele_nome: 'navigationButtons',
        ele_descricao: 'Botões de navegação',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480018',
        ele_nome: 'seal',
        ele_descricao: 'Selo/insígnia da oferta',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480019',
        ele_nome: 'benefits',
        ele_descricao: 'Lista de benefícios',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480020',
        ele_nome: 'pricing',
        ele_descricao: 'Informações de preço',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480021',
        ele_nome: 'contractButton',
        ele_descricao: 'Botão de contratação',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== SERVIÇOS ESSENCIAIS ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480022',
        ele_nome: 'title',
        ele_descricao: 'Título da seção',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480023',
        ele_nome: 'description',
        ele_descricao: 'Descrição da seção',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480024',
        ele_nome: 'cards',
        ele_descricao: 'Cards com serviços',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480025',
        ele_nome: 'icons',
        ele_descricao: 'Ícones dos serviços',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== CONTATO ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480026',
        ele_nome: 'form',
        ele_descricao: 'Formulário de contato',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480027',
        ele_nome: 'map',
        ele_descricao: 'Mapa com localização',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480028',
        ele_nome: 'phones',
        ele_descricao: 'Telefones de contato',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480029',
        ele_nome: 'email',
        ele_descricao: 'Email de contato',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480030',
        ele_nome: 'address',
        ele_descricao: 'Endereço físico',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== HELP SECTION ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480031',
        ele_nome: 'backgroundImage',
        ele_descricao: 'Imagem de fundo',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480035',
        ele_nome: 'buttons',
        ele_descricao: 'Botões/Cards de ação rápida',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ==================== FAQ ====================
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480032',
        ele_nome: 'search',
        ele_descricao: 'Barra de busca FAQ',
        ele_habilitado: true,
        ele_obrigatório: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480033',
        ele_nome: 'categories',
        ele_descricao: 'Categorias de FAQ',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        ele_id: '550e8400-e29b-41d4-a716-446655480034',
        ele_nome: 'accordion',
        ele_descricao: 'Acordeão de perguntas',
        ele_habilitado: true,
        ele_obrigatório: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await queryInterface.bulkInsert('0005_Elemento', elementos);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('0005_Elemento', null, {});
  },
};
