/** @type {import('sequelize-cli').Migration} */
export default {
  async up(queryInterface, Sequelize) {
    const conteudos = [
      // ============ ONI TELECOM - OFERTAS DE PLANOS (4) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550001',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 650 Mbps',
        cnt_descricao: 'Para sua empresa - Plano Premium',
        cnt_dados: JSON.stringify({
          id: 1,
          speed: 650,
          price: 999.99,
          header: 'Para sua empresa',
          cardType: 'card-completo',
          sealImgKey: 'carimbo gratis',
          featured: true,
          popular: false,
          benefits: [
            { imgKey: 'onigo', alt: 'Onigo', width: 240 },
            {
              type: 'sideBySide',
              images: [
                { imgKey: 'sky+', alt: 'Sky+' },
                { imgKey: 'max', alt: 'Max' },
              ],
            },
            { imgKey: 'playkids', alt: 'Playkids', width: 240 },
            { imgKey: 'deezer', alt: 'Deezer', width: 240 },
          ],
          appChoices: [
            { imgKey: 'onigo', alt: 'Onigo' },
            { imgKey: 'deezer', alt: 'Deezer' },
            { imgKey: 'playkids', alt: 'Playkids' },
            { imgKey: 'LOOKE', alt: 'Looke' },
          ],
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550002',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 500 Mbps',
        cnt_descricao: 'Para sua empresa - Plano Popular',
        cnt_dados: JSON.stringify({
          id: 2,
          speed: 500,
          price: 799.99,
          header: 'Para sua empresa',
          cardType: 'card-3-imagens',
          featured: false,
          popular: true,
          benefits: [
            { imgKey: 'onigo', alt: 'Onigo', width: 240 },
            { imgKey: 'playkids', alt: 'Playkids', width: 240 },
            { imgKey: 'deezer', alt: 'Deezer', width: 240 },
          ],
          appChoices: [
            { imgKey: 'onigo', alt: 'Onigo' },
            { imgKey: 'deezer', alt: 'Deezer' },
            { imgKey: 'playkids', alt: 'Playkids' },
            { imgKey: 'LOOKE', alt: 'Looke' },
          ],
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550003',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 350 Mbps',
        cnt_descricao: 'Para sua empresa - Plano Intermediário',
        cnt_dados: JSON.stringify({
          id: 3,
          speed: 350,
          price: 599.99,
          header: 'Para sua empresa',
          cardType: 'card-2-imagens',
          featured: false,
          popular: false,
          benefits: [
            {
              imgKey: 'onigo',
              alt: 'Onigo',
              width: 240,
              marginTop: 40,
              marginBottom: 40,
            },
            {
              imgKey: 'playkids',
              alt: 'Playkids',
              width: 240,
              marginTop: 40,
              marginBottom: 40,
            },
          ],
          appChoices: [
            { imgKey: 'onigo', alt: 'Onigo' },
            { imgKey: 'deezer', alt: 'Deezer' },
            { imgKey: 'playkids', alt: 'Playkids' },
            { imgKey: 'LOOKE', alt: 'Looke' },
          ],
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550004',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 200 Mbps',
        cnt_descricao: 'Para sua empresa - Plano Básico',
        cnt_dados: JSON.stringify({
          id: 4,
          speed: 200,
          price: 399.99,
          header: 'Para sua empresa',
          cardType: 'card-2-imagens',
          featured: false,
          popular: false,
          benefits: [
            {
              imgKey: 'onigo',
              alt: 'Onigo',
              width: 240,
              marginTop: 40,
              marginBottom: 40,
            },
            {
              imgKey: 'deezer',
              alt: 'Deezer',
              width: 240,
              marginTop: 40,
              marginBottom: 40,
            },
          ],
          appChoices: [
            { imgKey: 'onigo', alt: 'Onigo' },
            { imgKey: 'deezer', alt: 'Deezer' },
            { imgKey: 'playkids', alt: 'Playkids' },
            { imgKey: 'LOOKE', alt: 'Looke' },
          ],
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ INTERNET (4) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550005',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'internet',
        cnt_titulo: 'FAQ - O que é fibra óptica?',
        cnt_descricao: 'Pergunta frequente sobre tecnologia',
        cnt_dados: JSON.stringify({
          id: 'internet-1',
          question: 'O que é a fibra óptica da Oni?',
          answer:
            'A fibra óptica da Oni é uma tecnologia de transmissão de dados que utiliza filamentos de vidro ou polímeros para transmitir informações através de pulsos de luz. Oferecemos conexões de até 1 Gbps com alta estabilidade e baixa latência, ideal para streaming, jogos online e trabalho remoto.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550006',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'internet',
        cnt_titulo: 'FAQ - Planos de internet',
        cnt_descricao: 'Pergunta sobre planos disponíveis',
        cnt_dados: JSON.stringify({
          id: 'internet-2',
          question: 'Quais são os planos de internet disponíveis?',
          answer:
            'A Oni oferece diversos planos de internet fibra óptica, começando com 300 Mbps por R$99,90/mês, 500 Mbps por R$129,90/mês e 1 Gbps por R$199,90/mês. Todos os planos incluem instalação gratuita, roteador Wi-Fi de última geração e suporte técnico 24/7.',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550007',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'internet',
        cnt_titulo: 'FAQ - Verificar velocidade',
        cnt_descricao: 'Pergunta sobre testes de velocidade',
        cnt_dados: JSON.stringify({
          id: 'internet-3',
          question: 'Como verificar a velocidade da minha internet?',
          answer:
            'Você pode verificar a velocidade da sua internet através do nosso aplicativo Oni ou acessando o site speedtest.net. Para resultados mais precisos, recomendamos fazer o teste com o computador conectado diretamente ao roteador via cabo de rede.',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550008',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'internet',
        cnt_titulo: 'FAQ - Cobertura Oni',
        cnt_descricao: 'Pergunta sobre área de cobertura',
        cnt_dados: JSON.stringify({
          id: 'internet-4',
          question: 'A Oni cobre meu endereço?',
          answer:
            'A Oni está em constante expansão. Para verificar se seu endereço é atendido pela nossa rede de fibra óptica, acesse nosso site e informe seu CEP na página inicial ou entre em contato com nossa central de atendimento pelo 0800 888 9999.',
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ ONIPLAY (2) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550009',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'oniplay',
        cnt_titulo: 'FAQ - O que é OniPlay?',
        cnt_descricao: 'Pergunta sobre plataforma de streaming',
        cnt_dados: JSON.stringify({
          id: 'oniplay-1',
          question: 'O que é o OniPlay?',
          answer:
            'O OniPlay é nossa plataforma de streaming exclusiva que oferece acesso a filmes, séries, canais ao vivo e conteúdo sob demanda. Disponível para assinantes dos planos de internet da Oni, pode ser acessado em Smart TVs, smartphones, tablets e computadores.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550010',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'oniplay',
        cnt_titulo: 'FAQ - Acessar OniPlay',
        cnt_descricao: 'Pergunta sobre como acessar plataforma',
        cnt_dados: JSON.stringify({
          id: 'oniplay-2',
          question: 'Como acessar o OniPlay?',
          answer:
            'Para acessar o OniPlay, baixe o aplicativo na loja de aplicativos do seu dispositivo ou acesse play.oni.com.br. Faça login com os mesmos dados da sua conta Oni e comece a assistir imediatamente.',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ ONI 5G (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550011',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'oni5g',
        cnt_titulo: 'FAQ - Planos móveis Oni',
        cnt_descricao: 'Pergunta sobre planos de celular',
        cnt_dados: JSON.stringify({
          id: 'oni5g-1',
          question: 'Quais são os planos móveis da Oni?',
          answer:
            'A Oni oferece planos móveis 4G e 5G com diferentes franquias de dados, começando com 5GB por R$39,90/mês até planos ilimitados por R$99,90/mês. Todos incluem ligações ilimitadas para qualquer operadora e WhatsApp sem consumir dados.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ DADOS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550012',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'dados',
        cnt_titulo: 'FAQ - Alterar dados cadastrais',
        cnt_descricao: 'Pergunta sobre perfil do cliente',
        cnt_dados: JSON.stringify({
          id: 'dados-1',
          question: 'Como alterar meus dados cadastrais?',
          answer:
            'Para alterar seus dados cadastrais, acesse sua conta no site da Oni ou no aplicativo, vá até a seção "Meu Perfil" e selecione "Editar Informações". Após fazer as alterações necessárias, clique em "Salvar".',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ PLANOS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550013',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'planos',
        cnt_titulo: 'FAQ - Mudar plano',
        cnt_descricao: 'Pergunta sobre alteração de plano',
        cnt_dados: JSON.stringify({
          id: 'planos-1',
          question: 'Como mudar meu plano atual?',
          answer:
            'Para alterar seu plano, acesse sua conta no site da Oni ou no aplicativo, vá até "Meus Serviços" e selecione "Alterar Plano". Você verá as opções disponíveis para upgrade ou downgrade. As alterações são processadas em até 24 horas.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ INDICAÇÃO (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550014',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'indicacao',
        cnt_titulo: 'FAQ - Indique um Amigo',
        cnt_descricao: 'Pergunta sobre programa de indicação',
        cnt_dados: JSON.stringify({
          id: 'indicacao-1',
          question: 'Como funciona o programa Indique um Amigo?',
          answer:
            'No programa Indique um Amigo da Oni, você recebe R$50 de desconto na sua mensalidade para cada amigo que assinar um de nossos planos usando seu código de indicação. Seu amigo também ganha R$50 de desconto na primeira mensalidade.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ SEGURANÇA (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550015',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'seguranca',
        cnt_titulo: 'FAQ - Proteção de dados',
        cnt_descricao: 'Pergunta sobre segurança de dados',
        cnt_dados: JSON.stringify({
          id: 'seguranca-1',
          question: 'Como a Oni protege meus dados?',
          answer:
            'A Oni utiliza tecnologias avançadas de criptografia e segurança para proteger seus dados pessoais, seguindo rigorosamente a Lei Geral de Proteção de Dados (LGPD). Realizamos auditorias de segurança regularmente e nunca compartilhamos suas informações com terceiros sem seu consentimento.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ APLICATIVOS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550016',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'aplicativos',
        cnt_titulo: 'FAQ - Aplicativos disponíveis',
        cnt_descricao: 'Pergunta sobre aplicativos inclusos',
        cnt_dados: JSON.stringify({
          id: 'aplicativos-1',
          question: 'Quais aplicativos estão disponíveis?',
          answer:
            'Oferecemos diversos aplicativos parceiros como Estuda+, Hub, Kaspersky e Leitura 360. Você pode escolher até 2 aplicativos inclusos no seu plano sem custo adicional.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - FAQ SUPORTE (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550017',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'faq',
        cnt_categoria: 'suporte',
        cnt_titulo: 'FAQ - Como contatar suporte',
        cnt_descricao: 'Pergunta sobre canais de suporte',
        cnt_dados: JSON.stringify({
          id: 'suporte-1',
          question: 'Como entrar em contato com o suporte?',
          answer:
            'Nosso suporte está disponível 24/7 através do telefone 0800 700 7072, WhatsApp (83) 97601-0064, chat no site ou app Oni. Também oferecemos suporte via e-mail em suporte@onitelecom.com.br.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - DEPOIMENTOS (2) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550018',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'depoimento',
        cnt_categoria: 'clientes',
        cnt_titulo: 'Depoimento - João Silva',
        cnt_descricao: 'Cliente satisfeito de João Pessoa',
        cnt_dados: JSON.stringify({
          id: 1,
          name: 'João Silva',
          location: 'João Pessoa - PB',
          rating: 5,
          text: 'A internet da Oni é excelente! Nunca tive problemas e o suporte é muito atencioso.',
          date: '2025-01-15',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550019',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'depoimento',
        cnt_categoria: 'clientes',
        cnt_titulo: 'Depoimento - Maria Santos',
        cnt_descricao: 'Cliente satisfeita de Cabedelo',
        cnt_dados: JSON.stringify({
          id: 2,
          name: 'Maria Santos',
          location: 'Cabedelo - PB',
          rating: 5,
          text: 'Melhor custo-benefício da região. Recomendo!',
          date: '2025-01-10',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // REMOVIDO: DEPOIMENTOS EMPRESAS - não utilizado

      // ============ ONI TELECOM - HELP SECTION (3) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550021',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'helpSection',
        cnt_categoria: 'ajuda',
        cnt_titulo: 'Help - Perguntas Frequentes',
        cnt_descricao: 'Card FAQ no Help Section',
        cnt_dados: JSON.stringify({
          id: 'faq',
          title: 'Perguntas Frequentes',
          description:
            'Encontre respostas rápidas para suas dúvidas mais comuns',
          buttonText: 'Explorar FAQs',
          link: '/perguntasfrequentes',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550022',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'helpSection',
        cnt_categoria: 'ajuda',
        cnt_titulo: 'Help - Atendimento',
        cnt_descricao: 'Card Atendimento no Help Section',
        cnt_dados: JSON.stringify({
          id: 'atendimento',
          title: 'Atendimento',
          description: 'Fale diretamente com nossa equipe de suporte dedicada',
          buttonText: 'Iniciar Chat',
          link: 'whatsapp',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550023',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'helpSection',
        cnt_categoria: 'ajuda',
        cnt_titulo: 'Help - Nossos Planos',
        cnt_descricao: 'Card Planos no Help Section',
        cnt_dados: JSON.stringify({
          id: 'planos',
          title: 'Nossos Planos',
          description: 'Descubra o plano perfeito para suas necessidades',
          buttonText: 'Ver Planos',
          link: '/Planos',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - OFERTAS CHIPS (8) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550024',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Básico',
        cnt_descricao: 'Plano de chip básico',
        cnt_dados: JSON.stringify({
          nome: 'Plano Básico',
          features: [
            { icon: 'faWifi', text: '5GB de Internet' },
            { icon: 'faPhone', text: '100 minutos' },
            { icon: 'faCommentAlt', text: '100 SMS' },
          ],
          preco: 'R$ 29,99/mês',
          imagensCount: 1,
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550025',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Intermediário',
        cnt_descricao: 'Plano de chip intermediário',
        cnt_dados: JSON.stringify({
          nome: 'Plano Intermediário',
          features: [
            { icon: 'faWifi', text: '10GB de Internet' },
            { icon: 'faPhone', text: '200 minutos' },
            { icon: 'faCommentAlt', text: '200 SMS' },
          ],
          preco: 'R$ 49,99/mês',
          imagensCount: 2,
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550026',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Premium',
        cnt_descricao: 'Plano de chip premium',
        cnt_dados: JSON.stringify({
          nome: 'Plano Premium',
          features: [
            { icon: 'faWifi', text: '20GB de Internet' },
            { icon: 'faPhone', text: 'Ligações Ilimitadas' },
            { icon: 'faCommentAlt', text: 'SMS Ilimitados' },
          ],
          preco: 'R$ 79,99/mês',
          imagensCount: 3,
          destaque: 'Popular',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550027',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Família',
        cnt_descricao: 'Plano de chip para família',
        cnt_dados: JSON.stringify({
          nome: 'Plano Família',
          features: [
            { icon: 'faWifi', text: '30GB de Internet' },
            { icon: 'faPhone', text: 'Ligações Ilimitadas' },
            { icon: 'faCommentAlt', text: 'SMS Ilimitados' },
            { icon: 'faUsers', text: 'Até 4 linhas' },
          ],
          preco: 'R$ 129,99/mês',
          imagensCount: 1,
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550028',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Estudante',
        cnt_descricao: 'Plano de chip para estudantes',
        cnt_dados: JSON.stringify({
          nome: 'Plano Estudante',
          features: [
            { icon: 'faWifi', text: '15GB de Internet' },
            { icon: 'faPhone', text: '150 minutos' },
            { icon: 'faCommentAlt', text: 'SMS Ilimitados' },
            {
              icon: 'faGraduationCap',
              text: 'Acesso a plataformas educacionais',
            },
          ],
          preco: 'R$ 59,99/mês',
          imagensCount: 2,
        }),
        cnt_ordem: 5,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550029',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Empresarial',
        cnt_descricao: 'Plano de chip para empresas',
        cnt_dados: JSON.stringify({
          nome: 'Plano Empresarial',
          features: [
            { icon: 'faWifi', text: '50GB de Internet' },
            { icon: 'faPhone', text: 'Ligações Ilimitadas' },
            { icon: 'faCommentAlt', text: 'SMS Ilimitados' },
            { icon: 'faBriefcase', text: 'Suporte prioritário' },
          ],
          preco: 'R$ 199,99/mês',
          imagensCount: 3,
        }),
        cnt_ordem: 6,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550030',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Gamer',
        cnt_descricao: 'Plano de chip para gamers',
        cnt_dados: JSON.stringify({
          nome: 'Plano Gamer',
          features: [
            { icon: 'faWifi', text: '100GB de Internet' },
            { icon: 'faPhone', text: 'Ligações Ilimitadas' },
            { icon: 'faGamepad', text: 'Prioridade em jogos online' },
            { icon: 'faTachometerAlt', text: 'Baixa latência' },
          ],
          preco: 'R$ 149,99/mês',
          imagensCount: 1,
        }),
        cnt_ordem: 7,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550031',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'ofertasChips',
        cnt_categoria: 'chips',
        cnt_titulo: 'Chip - Plano Ilimitado Plus',
        cnt_descricao: 'Plano de chip ilimitado plus',
        cnt_dados: JSON.stringify({
          nome: 'Plano Ilimitado Plus',
          features: [
            { icon: 'faInfinity', text: 'Internet Ilimitada' },
            { icon: 'faPhone', text: 'Ligações Ilimitadas' },
            { icon: 'faCommentAlt', text: 'SMS Ilimitados' },
            { icon: 'faGlobe', text: 'Roaming internacional' },
          ],
          preco: 'R$ 249,99/mês',
          imagensCount: 2,
          destaque: 'Novo',
        }),
        cnt_ordem: 8,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - POR QUE ESCOLHER (3) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550032',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'porQueEscolher',
        cnt_categoria: 'recursos',
        cnt_titulo: 'Por Que Escolher - Atendimento Personalizado',
        cnt_descricao: 'Recurso de atendimento personalizado',
        cnt_dados: JSON.stringify({
          icon: 'faUserTie',
          titulo: 'Atendimento Personalizado',
          descricao:
            'Conte com um gerente de conta dedicado para atender às necessidades específicas da sua empresa.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550033',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'porQueEscolher',
        cnt_categoria: 'recursos',
        cnt_titulo: 'Por Que Escolher - Soluções Integradas',
        cnt_descricao: 'Recurso de soluções integradas',
        cnt_dados: JSON.stringify({
          icon: 'faCogs',
          titulo: 'Soluções Integradas',
          descricao:
            'Simplifique sua gestão de telecom com nossas soluções completas e integradas.',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550034',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'porQueEscolher',
        cnt_categoria: 'recursos',
        cnt_titulo: 'Por Que Escolher - Suporte 24/7',
        cnt_descricao: 'Recurso de suporte 24/7',
        cnt_dados: JSON.stringify({
          icon: 'faHeadset',
          titulo: 'Suporte 24/7',
          descricao:
            'Suporte técnico especializado disponível 24 horas por dia, 7 dias por semana.',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - SERVIÇOS (5) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550035',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicos',
        cnt_categoria: 'empresarial',
        cnt_titulo: 'Serviço - Internet Empresarial',
        cnt_descricao: 'Serviço de internet para empresas',
        cnt_dados: JSON.stringify({
          icon: 'faGlobe',
          titulo: 'Internet Empresarial',
          descricao:
            'Conexão rápida e estável para manter sua empresa sempre online.',
          recursos: [
            'Fibra óptica de última geração',
            'Planos dedicados com garantia de banda',
            'Suporte técnico 24/7',
          ],
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550036',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicos',
        cnt_categoria: 'empresarial',
        cnt_titulo: 'Serviço - Telefonia Empresarial',
        cnt_descricao: 'Serviço de telefonia para empresas',
        cnt_dados: JSON.stringify({
          icon: 'faPhoneAlt',
          titulo: 'Telefonia Empresarial',
          descricao:
            'Comunicação clara e eficiente para sua equipe e clientes.',
          recursos: [
            'PABX na nuvem',
            'Ramais ilimitados',
            'Integração com CRM',
          ],
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550037',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicos',
        cnt_categoria: 'empresarial',
        cnt_titulo: 'Serviço - Mobilidade Corporativa',
        cnt_descricao: 'Serviço de mobilidade corporativa',
        cnt_dados: JSON.stringify({
          icon: 'faMobileAlt',
          titulo: 'Mobilidade Corporativa',
          descricao: 'Mantenha sua equipe conectada em qualquer lugar.',
          recursos: [
            'Planos corporativos flexíveis',
            'Gestão online de linhas',
            'Roaming internacional',
          ],
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550038',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicos',
        cnt_categoria: 'empresarial',
        cnt_titulo: 'Serviço - TV Corporativa',
        cnt_descricao: 'Serviço de TV para empresas',
        cnt_dados: JSON.stringify({
          icon: 'faTv',
          titulo: 'TV Corporativa',
          descricao: 'Informação e entretenimento para sua empresa e clientes.',
          recursos: [
            'Canais corporativos personalizados',
            'Pacotes de notícias e negócios',
            'Soluções para hotéis e academias',
          ],
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550039',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicos',
        cnt_categoria: 'empresarial',
        cnt_titulo: 'Serviço - Sistemas de Segurança',
        cnt_descricao: 'Serviço de sistemas de segurança',
        cnt_dados: JSON.stringify({
          icon: 'faVideo',
          titulo: 'Sistemas de Segurança',
          descricao: 'Proteção avançada para seu patrimônio e colaboradores.',
          recursos: [
            'Câmeras IP de alta definição',
            'Armazenamento em nuvem',
            'Acesso remoto via aplicativo',
          ],
        }),
        cnt_ordem: 5,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - SERVIÇOS ESSENCIAIS (4) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550040',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicosEssenciais',
        cnt_categoria: 'suporte',
        cnt_titulo: 'Serviço Essencial - Consulte sua fatura',
        cnt_descricao: 'Link para consultar fatura',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'img1',
          text: 'Consulte sua fatura',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550041',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicosEssenciais',
        cnt_categoria: 'suporte',
        cnt_titulo: 'Serviço Essencial - Tire suas dúvidas',
        cnt_descricao: 'Link para tirar dúvidas',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'img2',
          text: 'Tire suas dúvidas',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550042',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicosEssenciais',
        cnt_categoria: 'suporte',
        cnt_titulo: 'Serviço Essencial - Fale conosco',
        cnt_descricao: 'Link para falar conosco',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'img3',
          text: 'Fale conosco',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550043',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servicosEssenciais',
        cnt_categoria: 'suporte',
        cnt_titulo: 'Serviço Essencial - Faça uma recarga',
        cnt_descricao: 'Link para fazer recarga',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'img4',
          text: 'Faça uma recarga',
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - CARDS ENTRETENIMENTO (5) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550048',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'cardsEntretenimento',
        cnt_categoria: 'entretenimento',
        cnt_titulo: 'Entretenimento - DEEZER',
        cnt_descricao: 'Card DEEZER',
        cnt_dados: JSON.stringify({
          id: 'deezer',
          name: 'DEEZER',
          price: '22,90',
          description:
            'Streaming de áudio para mais música no seu dia-a-dia! Escute seus artistas, podcasts e playlists favoritos, descubra novos gostos, conheça os conteúdos exclusivos da Deezer e aproveite mais de 120 milhões de faixas do mundo todo.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550049',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'cardsEntretenimento',
        cnt_categoria: 'entretenimento',
        cnt_titulo: 'Entretenimento - DUOLINGO',
        cnt_descricao: 'Card DUOLINGO',
        cnt_dados: JSON.stringify({
          id: 'duolingo',
          name: 'DUOLINGO',
          price: '29,90',
          description:
            'Aprenda idiomas de forma divertida e eficaz! O Duolingo oferece lições interativas, desafios diários e um sistema de gamificação para manter você motivado enquanto aprende uma nova língua.',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550050',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'cardsEntretenimento',
        cnt_categoria: 'entretenimento',
        cnt_titulo: 'Entretenimento - NORDVPN',
        cnt_descricao: 'Card NORDVPN',
        cnt_dados: JSON.stringify({
          id: 'nordvpn',
          name: 'NORDVPN',
          price: '19,90',
          description:
            'Proteja sua privacidade online com o NordVPN. Navegue com segurança, acesse conteúdo bloqueado geograficamente e mantenha seus dados pessoais protegidos com criptografia de nível militar.',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550051',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'cardsEntretenimento',
        cnt_categoria: 'entretenimento',
        cnt_titulo: 'Entretenimento - CALM',
        cnt_descricao: 'Card CALM',
        cnt_dados: JSON.stringify({
          id: 'calm',
          name: 'CALM',
          price: '34,90',
          description:
            'Melhore seu bem-estar mental com o Calm. Acesse meditações guiadas, histórias para dormir, músicas relaxantes e exercícios de respiração para reduzir o estresse e melhorar a qualidade do seu sono.',
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ INTERNET BRASIL - OFERTAS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550052',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450002',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 500 Mbps',
        cnt_descricao: 'Para sua região',
        cnt_dados: JSON.stringify({
          speed: 500,
          price: 599.99,
          featured: true,
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ OLINE NET - OFERTAS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550053',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450003',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 300 Mbps',
        cnt_descricao: 'Para sua região',
        cnt_dados: JSON.stringify({
          speed: 300,
          price: 399.99,
          featured: true,
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ WIL TELECOM - OFERTAS (1) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550054',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450004',
        cnt_tipo: 'oferta',
        cnt_categoria: 'planos',
        cnt_titulo: 'Plano 400 Mbps',
        cnt_descricao: 'Para sua região',
        cnt_dados: JSON.stringify({
          speed: 400,
          price: 499.99,
          featured: true,
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - SERVIÇOS ESSENCIAIS (4) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550103',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'card',
        cnt_categoria: 'servicosEssenciais',
        cnt_titulo: 'Consulte sua fatura',
        cnt_descricao: 'Link para consulta de fatura via WhatsApp',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'consultaFatura',
          text: 'Consulte sua fatura',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550104',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'card',
        cnt_categoria: 'servicosEssenciais',
        cnt_titulo: 'Tire suas dúvidas',
        cnt_descricao: 'Link para tirar dúvidas via WhatsApp',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'duvidas',
          text: 'Tire suas dúvidas',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550105',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'card',
        cnt_categoria: 'servicosEssenciais',
        cnt_titulo: 'Fale conosco',
        cnt_descricao: 'Link para contato via WhatsApp',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'faleConosco',
          text: 'Fale conosco',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550106',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'card',
        cnt_categoria: 'servicosEssenciais',
        cnt_titulo: 'Faça uma recarga',
        cnt_descricao: 'Link para recarga via WhatsApp',
        cnt_dados: JSON.stringify({
          href: 'https://api.whatsapp.com/send/?phone=5583976010064&text&type=phone_number&app_absent=0',
          imgKey: 'recarga',
          text: 'Faça uma recarga',
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // ============ ONI TELECOM - SERVIÇOS ESSENCIAIS INTERNET (4) ============
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550107',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servico',
        cnt_categoria: 'servicosEssenciaisInternet',
        cnt_titulo: 'Conexão 100% Fibra Óptica',
        cnt_descricao: 'Serviço de conexão fibra óptica',
        cnt_dados: JSON.stringify({
          imgKey: 'fibraOptica',
          alt: 'Fibra Óptica',
          titulo: 'CONEXÃO 100% FIBRA ÓPTICA',
          descricao:
            'Experimente velocidades ultrarrápidas e estabilidade incomparável com nossa rede de fibra óptica de ponta a ponta.',
        }),
        cnt_ordem: 1,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550108',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servico',
        cnt_categoria: 'servicosEssenciaisInternet',
        cnt_titulo: 'Roteador Wi-Fi Dual Band',
        cnt_descricao: 'Serviço de roteador Wi-Fi',
        cnt_dados: JSON.stringify({
          imgKey: 'roteadorWifi',
          alt: 'Roteador Wi-Fi',
          titulo: 'ROTEADOR WI-FI DUAL BAND',
          descricao:
            'Desfrute de uma cobertura Wi-Fi ampla e potente em toda sua casa com nosso roteador de última geração.',
        }),
        cnt_ordem: 2,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550109',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servico',
        cnt_categoria: 'servicosEssenciaisInternet',
        cnt_titulo: 'Suporte Técnico Avançado',
        cnt_descricao: 'Serviço de suporte técnico',
        cnt_dados: JSON.stringify({
          imgKey: 'suporteTecnico',
          alt: 'Suporte',
          titulo: 'SUPORTE TÉCNICO AVANÇADO',
          descricao:
            'Conte com nossa equipe de especialistas 24/7 para resolver qualquer problema e otimizar sua conexão.',
        }),
        cnt_ordem: 3,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        cnt_id: '550e8400-e29b-41d4-a716-446655550110',
        cnt_tem_id: '550e8400-e29b-41d4-a716-446655450001',
        cnt_tipo: 'servico',
        cnt_categoria: 'servicosEssenciaisInternet',
        cnt_titulo: 'Equipe Especializada',
        cnt_descricao: 'Serviço de equipe especializada',
        cnt_dados: JSON.stringify({
          imgKey: 'equipeEspecializada',
          alt: 'Equipe Especializada',
          titulo: 'EQUIPE ESPECIALIZADA',
          descricao:
            'Nossos profissionais altamente treinados garantem a melhor experiência em instalação e manutenção.',
        }),
        cnt_ordem: 4,
        cnt_habilitado: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await queryInterface.bulkInsert('0012_Conteudo', conteudos);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('0012_Conteudo', null, {});
  },
};
